# Setup
title:               Blog
tagline:             'A Window Into My Thoughts'
description:         
url:                 https://abhip64.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Abhijith Prakash
  url:               https://abhip64.github.io/
  email:             abhijithprakash64@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
